name: config
description: "Provide config functionality for the app"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  dependencies:
    path: ../dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - .env_dev
    - .env_prod
  #   - assets/images/
  #   - assets/vectors/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/poppins_italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/poppins/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/poppins_semibold.ttf
          weight: 600
        - asset: assets/fonts/poppins/poppins_bold.ttf
          weight: 700
